import type { ItemPageProps } from './Item';

export type ItemId =
  | '1'
  | '2'
  | '3'
  | '4'
  | '5'
  | '6'
  | '7'
  | '8'
  | '9'
  | '10'
  | '11'
  | '12'
  | '13'
  | '14'
  | '15'
  | '16'
  | '17'
  | '18'
  | '19'
  | '20'
  | '21'
  | '22'
  | '23'
  | '24';

export const ITEMS: Record<ItemId, ItemPageProps> = {
  '23': {
    title: 'МОДУЛЬ 2.1',
    second: '9',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 450/400/300',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 21945,
    gallery: [
      '/item/m2.1/smallGallery/1.png',
      '/item/m2.1/smallGallery/2.png',
      '/item/m2.1/smallGallery/3.png',
      '/item/m2.1/smallGallery/4.png',
      '/item/m2.1/smallGallery/5.png',
    ],
    compatibility: '/item/m2.1/comb.svg',
    comboTitle: 'М2.1',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m2.1/bigGallery/1.png',
      '/item/m2.1/bigGallery/2.png',
      '',
      '/item/m2.1/bigGallery/3.png',
      '/item/m2.1/bigGallery/4.png',
      '/item/m2.1/bigGallery/5.png',
    ],
  },
  '1': {
    title: 'МОДУЛЬ 1',
    second: '21',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Габаритные размеры:Ш/Г/В - 900/400/200',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 12540,
    gallery: [
      '/item/item1/gallery1.png',
      '/item/item1/gallery2.png',
      '/item/item1/gallery3.png',
      '/item/item1/gallery4.png',
      '/item/item1/gallery5.png',
    ],
    compatibility: '/item/item1/combo.svg',
    comboTitle: 'М1',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/item1/galleryB1.png',
      '/item/item1/galleryB4.png',
      '/item/item1/galleryB2.png',
      '/item/item1/galleryB5.png',
      '/item/item1/galleryB3.png',
      '/item/item1/galleryB6.png',
    ],
  },
  '21': {
    title: 'МОДУЛЬ 1.1',
    second: '1',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Изделие приходит в собранном виде',
      'Габаритные размеры: Ш/Г/В - 450/400/200',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 13585,
    gallery: [
      '/item/m1.1/smallGallery/1.png',
      '/item/m1.1/smallGallery/2.png',
      '/item/m1.1/smallGallery/3.png',
      '/item/m1.1/smallGallery/4.png',
      '/item/m1.1/smallGallery/5.png',
    ],
    compatibility: '/item/m1.1/comb.svg',
    comboTitle: 'М1.1',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m1.1/bigGallery/1.png',
      '/item/m1.1/bigGallery/2.png',
      '',
      '/item/m1.1/bigGallery/3.jpg',
      '/item/m1.1/bigGallery/4.png',
      '/item/m1.1/bigGallery/5.png',
    ],
  },
  '22': {
    title: 'МОДУЛЬ 2.5',
    second: '10',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/300',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 29260,
    gallery: [
      '/item/m2.5/smallGallery/1.png',
      '/item/m2.5/smallGallery/2.png',
      '/item/m2.5/smallGallery/3.png',
      '/item/m2.5/smallGallery/4.png',
      '/item/m2.5/smallGallery/5.png',
    ],
    compatibility: '/item/m2.5/comb.svg',
    comboTitle: 'М2.5',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m2.5/bigGallery/1.png',
      '/item/m2.5/bigGallery/2.png',
      '/item/m2.5/bigGallery/3.png',
      '/item/m2.5/bigGallery/4.png',
      '',
      '/item/m2.5/bigGallery/5.png',
    ],
  },
  '7': {
    title: 'МОДУЛЬ 1.2',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Изделие приходит в собранном виде',
      'Габаритные размеры: Ш/Г/В - 450/400/200',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 19855,
    gallery: [
      '/item/m1.2/smallGallery/1.png',
      '/item/m1.2/smallGallery/2.png',
      '/item/m1.2/smallGallery/3.png',
      '/item/m1.2/smallGallery/4.png',
      '/item/m1.2/smallGallery/5.png',
    ],
    compatibility: '/item/m1.2/comb.svg',
    comboTitle: 'M1.2',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m1.2/bigGallery/1.png',
      '/item/m1.2/bigGallery/2.png',
      '/item/m1.2/bigGallery/3.png',
      '/item/m1.2/bigGallery/4.png',
      '/item/m1.2/bigGallery/5.png',
    ],
  },

  '11': {
    title: 'Подножье 1',
    specs: [
      'Подножье ',
      'Материал : массив берёзы',
      'Материал фасадов: прозрачное рифлёное стекло 4мм',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 450/400/200',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
      'Изделие приходит в разобранном виде',
    ],
    price: 9405,
    gallery: [
      '/item/p1/smallGallery/1.png',
      '/item/p1/smallGallery/2.png',
      '/item/p1/smallGallery/3.png',
      '/item/p1/smallGallery/4.png',
      '/item/p1/smallGallery/5.png',
    ],
    compatibility: '/item/p1/comb.svg',
    comboTitle: 'П1',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/p1/bigGallery/1.png',
      '/item/p1/bigGallery/2.png',
      '/item/p1/bigGallery/3.png',
      '/item/p1/bigGallery/4.png',
      '/item/p1/bigGallery/5.png',
      '/item/p1/bigGallery/6.png',
    ],
  },

  '17': {
    title: 'Подножье 2',
    specs: [
      'Подножье ',
      'Материал : массив берёзы',
      'Материал фасадов: прозрачное рифлёное стекло 4мм',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 450/400/400',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
      'Изделие приходит в разобранном виде',
    ],
    price: 15675,
    gallery: [
      '/item/p2/smallGallery/1.png',
      '/item/p2/smallGallery/2.png',
      '/item/p2/smallGallery/3.png',
      '/item/p2/smallGallery/4.png',
      '/item/p2/smallGallery/5.png',
    ],
    compatibility: '/item/p2/comb.svg',
    comboTitle: 'П2',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/p2/bigGallery/1.png',
      '/item/p2/bigGallery/2.png',
      '/item/p2/bigGallery/3.png',
      '/item/p2/bigGallery/4.png',
      '/item/p2/bigGallery/5.png',
      '/item/p2/bigGallery/6.png',
    ],
  },
  //2столб
  '2': {
    title: 'Модуль 1.3',
    second: '24',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/200',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 18810,
    gallery: [
      '/item/m1.3/smallGallery/1.png',
      '/item/m1.3/smallGallery/2.png',
      '/item/m1.3/smallGallery/3.png',
      '/item/m1.3/smallGallery/4.png',
      '/item/m1.3/smallGallery/5.png',
    ],
    compatibility: '/item/m1.3/comb.svg',
    comboTitle: 'М1.3',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m1.3/bigGallery/1.png',
      '/item/m1.3/bigGallery/2.png',
      '/item/m1.3/bigGallery/3.png',
      '/item/m1.3/bigGallery/5.png',
      '/item/m1.3/bigGallery/6.png',
      '/item/m1.3/bigGallery/4.png',
    ],
  },
  '24': {
    title: 'МОДУЛЬ 1.4',
    second: '2',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/200',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 19855,
    gallery: [
      '/item/m1.4/smallGallery/1.png',
      '/item/m1.4/smallGallery/2.png',
      '/item/m1.4/smallGallery/3.png',
      '/item/m1.4/smallGallery/4.png',
      '/item/m1.4/smallGallery/5.png',
    ],
    compatibility: '/item/m1.4/comb.svg',
    comboTitle: 'М1.4',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m1.4/bigGallery/1.png',
      '/item/m1.4/bigGallery/2.png',
      '/item/m1.4/bigGallery/3.png',
      '/item/m1.4/bigGallery/4.png',
      '',
      '/item/m1.4/bigGallery/5.png',
    ],
  },
  '12': {
    title: 'Подножье 1.1',
    specs: [
      'Подножье ',
      'Материал : массив берёзы',
      'Материал фасадов: прозрачное рифлёное стекло 4мм',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/200',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
      'Изделие приходит в разобранном виде',
    ],
    price: 10450,
    gallery: [
      '/item/p1.1/smallGallery/1.png',
      '/item/p1.1/smallGallery/2.png',
      '/item/p1.1/smallGallery/3.png',
      '/item/p1.1/smallGallery/4.png',
      '/item/p1.1/smallGallery/5.png',
    ],
    compatibility: '/item/p1.1/comb.svg',
    comboTitle: 'П1.1',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/p1.1/bigGallery/1.png',
      '/item/p1.1/bigGallery/2.png',
      '/item/p1.1/bigGallery/3.png',
      '/item/p1.1/bigGallery/4.png',
      '/item/p1.1/bigGallery/5.png',
      '/item/p1.1/bigGallery/6.png',
    ],
  },
  '18': {
    title: 'Подножье 2.1',
    specs: [
      'Подножье ',
      'Материал : массив берёзы',
      'Материал фасадов: прозрачное рифлёное стекло 4мм',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 450/400/400',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
      'Изделие приходит в разобранном виде',
    ],
    price: 18810,
    gallery: [
      '/item/p2.2/smallGallery/1.png',
      '/item/p2.2/smallGallery/2.png',
      '/item/p2.2/smallGallery/3.png',
      '/item/p2.2/smallGallery/4.png',
      '/item/p2.2/smallGallery/5.png',
    ],
    compatibility: '/item/p2.2/comb.svg',
    comboTitle: 'П2.2',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/p2.2/bigGallery/1.png',
      '/item/p2.2/bigGallery/2.png',
      '/item/p2.2/bigGallery/3.png',
      '/item/p2.2/bigGallery/4.png',
      '/item/p2.2/bigGallery/5.png',
      '/item/p2.2/bigGallery/6.png',
    ],
  },
  //3 столб
  '3': {
    title: 'СТОЛЕШНИЦА МАЛАЯ',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 450/400/40',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 6270,
    gallery: [
      '/item/sm/smallGallery/1.png',
      '/item/sm/smallGallery/2.png',
      '/item/sm/smallGallery/3.png',
      '/item/sm/smallGallery/4.png',
      '/item/sm/smallGallery/5.png',
    ],
    compatibility: '/item/sm/comb.svg',
    comboTitle: 'СМ',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/sm/bigGallery/1.png',
      '/item/sm/bigGallery/2.png',
      '/item/sm/bigGallery/3.png',
      '/item/sm/bigGallery/4.png',
      '/item/sm/bigGallery/5.png',
      '/item/sm/bigGallery/6.png',
    ],
  },
  '9': {
    title: 'МОДУЛЬ 2',
    second: '23',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 450/400/300',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 15675,
    gallery: [
      '/item/m2/smallGallery/1.png',
      '/item/m2/smallGallery/2.png',
      '/item/m2/smallGallery/3.png',
      '/item/m2/smallGallery/4.png',
      '/item/m2/smallGallery/5.png',
    ],
    compatibility: '/item/m2/comb.svg',
    comboTitle: 'М2',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m2/bigGallery/1.png',
      '/item/m2/bigGallery/2.png',
      '/item/m2/bigGallery/3.png',
      '/item/m2/bigGallery/4.png',
      '/item/m2/bigGallery/5.png',
      '/item/m2/bigGallery/6.png',
    ],
  },
  '13': {
    title: 'МОДУЛЬ 2.2',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 450/400/300',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 17100,
    gallery: [
      '/item/m2.2/smallGallery/1.png',
      '/item/m2.2/smallGallery/2.png',
      '/item/m2.2/smallGallery/3.png',
      '/item/m2.2/smallGallery/4.png',
      '/item/m2.2/smallGallery/5.png',
    ],
    compatibility: '/item/m2.2/comb.svg',
    comboTitle: 'М2.2',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m2.2/bigGallery/1.png',
      '/item/m2.2/bigGallery/2.png',
      '/item/m2.2/bigGallery/3.png',
      '/item/m2.2/bigGallery/4.png',
      '/item/m2.2/bigGallery/5.png',
    ],
  },

  '19': {
    title: 'МОДУЛЬ 2.3',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 450/400/300',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 18810,
    gallery: [
      '/item/m2.3/smallGallery/1.png',
      '/item/m2.3/smallGallery/2.png',
      '/item/m2.3/smallGallery/3.png',
      '/item/m2.3/smallGallery/4.png',
      '/item/m2.3/smallGallery/5.png',
      '/item/m2.3/smallGallery/6.png',
    ],
    compatibility: '/item/m2.3/comb.svg',
    comboTitle: 'М2.3',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m2.3/bigGallery/1.png',
      '/item/m2.3/bigGallery/2.png',
      '/item/m2.3/bigGallery/5.png',
      '/item/m2.3/bigGallery/3.png',
      '/item/m2.3/bigGallery/4.png',
    ],
  },

  //4 столб
  '4': {
    title: 'СТОЛЕШНИЦА БОЛЬШАЯ',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/40',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 9405,
    gallery: [
      '/item/sb/smallGallery/1.png',
      '/item/sb/smallGallery/2.png',
      '/item/sb/smallGallery/3.png',
      '/item/sb/smallGallery/4.png',
      '/item/sb/smallGallery/5.png',
    ],
    compatibility: '/item/sb/comb.svg',
    comboTitle: 'СБ',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/sb/bigGallery/1.png',
      '/item/sb/bigGallery/2.png',
      '/item/sb/bigGallery/3.png',
      '/item/sb/bigGallery/4.png',
      '',
      '/item/sb/bigGallery/5.png',
    ],
  },
  '10': {
    title: 'МОДУЛЬ 2.4',
    second: '22',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/300',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 20900,
    gallery: [
      '/item/m2.4/smallGallery/1.png',
      '/item/m2.4/smallGallery/2.png',
      '/item/m2.4/smallGallery/3.png',
      '/item/m2.4/smallGallery/4.png',
      '/item/m2.4/smallGallery/5.png',
    ],
    compatibility: '/item/m2.4/comb.svg',
    comboTitle: 'М2.4',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m2.4/bigGallery/1.png',
      '/item/m2.4/bigGallery/2.png',
      '/item/m2.4/bigGallery/3.png',
      '/item/m2.4/bigGallery/4.png',
      '',
      '/item/m2.4/bigGallery/5.png',
      '/item/m2.4/bigGallery/6.png',
    ],
  },

  '14': {
    title: 'МОДУЛЬ 2.6',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/300',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 29260,
    gallery: [
      '/item/m2.6/smallGallery/1.png',
      '/item/m2.6/smallGallery/2.png',
      '/item/m2.6/smallGallery/3.png',
      '/item/m2.6/smallGallery/4.png',
      '/item/m2.6/smallGallery/5.png',
    ],
    compatibility: '/item/m2.6/comb.svg',
    comboTitle: 'М2.6',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m2.6/bigGallery/1.png',
      '/item/m2.6/bigGallery/2.png',
      '/item/m2.6/bigGallery/3.png',
      '/item/m2.6/bigGallery/4.png',
      '',
      '/item/m2.6/bigGallery/5.png',
    ],
  },
  '20': {
    title: 'МОДУЛЬ 2.7',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/300',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 26125,
    gallery: [
      '/item/m2.7/smallGallery/1.png',
      '/item/m2.7/smallGallery/2.png',
      '/item/m2.7/smallGallery/3.png',
      '/item/m2.7/smallGallery/4.png',
      '/item/m2.7/smallGallery/5.png',
    ],
    compatibility: '/item/m2.7/comb.svg',
    comboTitle: 'М2.7',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m2.7/bigGallery/1.png',
      '/item/m2.7/bigGallery/2.png',
      '/item/m2.7/bigGallery/3.png',
      '/item/m2.7/bigGallery/4.png',
      '',
      '/item/m2.7/bigGallery/5.png',
    ],
  },
  //5 столб
  '5': {
    title: 'ВИТРИНА МАЛАЯ',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Материал фасадов: прозрачное рифлёное стекло 4мм',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/642',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
      'Изделие приходит в собранном виде',
    ],
    price: 52250,
    gallery: [
      '/item/vm/smallGallery/1.png',
      '/item/vm/smallGallery/2.png',
      '/item/vm/smallGallery/3.png',
      '/item/vm/smallGallery/4.png',
      '/item/vm/smallGallery/5.png',
      '/item/vm/smallGallery/6.png',
    ],
    compatibility: '/item/vm/comb.svg',
    comboTitle: 'ВМ',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/vm/bigGallery/1.png',
      '/item/vm/bigGallery/2.png',
      '/item/vm/bigGallery/3.png',
      '/item/vm/bigGallery/4.png',
      '/item/vm/bigGallery/5.png',
      '/item/vm/bigGallery/6.png',
    ],
  },

  '15': {
    title: 'ВИТРИНА БОЛЬШАЯ',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Материал фасадов: прозрачное рифлёное стекло 4мм',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/1284',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
      'Изделие приходит в собранном виде',
    ],
    price: 73150,
    gallery: [
      '/item/vb/smallGallery/1.png',
      '/item/vb/smallGallery/2.png',
      '/item/vb/smallGallery/3.png',
      '/item/vb/smallGallery/4.png',
      '/item/vb/smallGallery/5.png',
      '/item/vb/smallGallery/6.png',
    ],
    compatibility: '/item/vb/comb.svg',
    comboTitle: 'ВБ',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/vb/bigGallery/1.png',
      '/item/vb/bigGallery/2.png',
      '/item/vb/bigGallery/3.png',
      '/item/vb/bigGallery/4.png',
      '/item/vb/bigGallery/5.png',
      '/item/vb/bigGallery/6.png',
    ],
  },
  //6 столб
  '6': {
    title: 'СТЕЛЛАЖ МАЛЫЙ',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Материал фасадов: прозрачное рифлёное стекло 4мм',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/642',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
      'Изделие приходит в собранном виде',
    ],
    price: 26125,
    gallery: [
      '/item/stm/smallGallery/1.png',
      '/item/stm/smallGallery/2.png',
      '/item/stm/smallGallery/3.png',
      '/item/stm/smallGallery/4.png',
      '/item/stm/smallGallery/5.png',
    ],
    compatibility: '/item/stm/comb.svg',
    comboTitle: 'СТМ',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/stm/bigGallery/1.png',
      '/item/stm/bigGallery/2.png',
      '/item/stm/bigGallery/3.png',
      '/item/stm/bigGallery/4.png',
      '/item/stm/bigGallery/5.png',
      '/item/stm/bigGallery/6.png',
    ],
  },
  '16': {
    title: 'СТЕЛЛАЖ БОЛЬШОЙ',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Материал фасадов: прозрачное рифлёное стекло 4мм',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/1284',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
      'Изделие приходит в собранном виде',
    ],
    price: 41800,
    gallery: [
      '/item/stb/smallGallery/1.png',
      '/item/stb/smallGallery/2.png',
      '/item/stb/smallGallery/3.png',
      '/item/stb/smallGallery/4.png',
      '/item/stb/smallGallery/5.png',
    ],
    compatibility: '/item/stb/comb.svg',
    comboTitle: 'СТБ',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/stb/bigGallery/1.png',
      '/item/stb/bigGallery/2.png',
      '/item/stb/bigGallery/3.png',
      '/item/stb/bigGallery/4.png',
      '/item/stb/bigGallery/5.png',
      '/item/stb/bigGallery/6.png',
    ],
  },
  '8': {
    title: 'МОДУЛЬ 1.5',
    specs: [
      'Базовый модуль коллекции',
      'Материал корпуса: берёзовая фанера',
      'Материал крепёжной рамы: массив берёзы',
      'Покрытие: масло Borma',
      'Цвет: Стандарт',
      'Габаритные размеры: Ш/Г/В - 900/400/200',
      'Изделие приходит в собранном виде',
    ],
    conditions: [
      'Изготовим предмет за две недели',
      'Доставим бесплатно по Казани',
      'Делим оплату на две части: 70% – при покупке, 30% – по готовности',
    ],
    price: 27170,
    gallery: [
      '/item/m1.5/smallGallery/1.png',
      '/item/m1.5/smallGallery/2.png',
      '/item/m1.5/smallGallery/3.png',
      '/item/m1.5/smallGallery/4.png',
      '/item/m1.5/smallGallery/5.png',
    ],
    compatibility: '/item/m1.5/comb.svg',
    comboTitle: 'М1.5',
    compatibilityMobile: undefined,
    bigGallery: [
      '/item/m1.5/bigGallery/1.png',
      '/item/m1.5/bigGallery/2.png',
      '/item/m1.5/bigGallery/3.png',
      '/item/m1.5/bigGallery/4.png',
      '',
      '/item/m1.5/bigGallery/5.png',
    ],
  },
};

export function getItemById(id: string | undefined): ItemPageProps {
  if (!id) return ITEMS['1'];
  return (ITEMS as Record<string, ItemPageProps>)[id] ?? ITEMS['1'];
}
